### ISSUE TITLE
Publish to Modrinth, GH Actions

### ISSUE THREAD

**Issue by MathiasDPX** [JoJjjo174/jlevels#3]
https://github.com/marketplace/actions/upload-to-modrinth

You can use secrets to hide your token

**Comment by JoJjjo174** [comment]
what do you mean? If you mean the project id, it's public, i don't think you could do anything malicious with that 😅

```
if (isOutdated("ZucF3Myf")) {
    outdated = true;
}
```

**Comment by MathiasDPX** [comment]
No, to automatically publish it to modrinth
- New release
- On modrinth in less than a minute

**Comment by JoJjjo174** [comment]
Oh ok, I'll have a look at it, ty
